# Hello there, I'm your first Ruby file! 🎉
# Run me from your terminal with `ruby test/welcome.rb`, or `load "test/welcome.rb"` if you are on Repl.it
# Please, DO NOT edit this file directly, but create new ones inside the test folder 👈

puts "Welcome to Le Wagon"
puts "Let's play with some Ruby!"
